name: Repository Events
on:
  push:
  pull_request:
    types: [opened, assigned, reopened]  
  issues:
    types: [opened, closed]
    
jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_REF
          echo $GITHUB_SHA
      - uses: actions/checkout@v3       