name: Reusable Workflow
on:
  workflow_dispatch:
    
jobs:
  generate-output:
    runs-on: ubuntu-latest
    steps:
      - run: echo "date=$(date)"
        id: date-step
      - run: echo $GITHUB_OUTPUT
