name: test-workflow
on: [push]


jobs:
  simple-shell-job:
    runs-on: ubuntu-latest
    steps:
      - name: run a shell command
        run: pwd

      - name: echo a string
        run: |
          ls
          npm -v  
          
  Dependent-Job:
    runs-on: windows-latest
    needs: simple-shell-job
    steps:
      - name: echo Output on Windows
        run: Write-Output "From Windows"  
        
