
name: Variables and Secrets
on: [push]
jobs:
  decrypt-file:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt File
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/secret.json secret.json.gpg
      - name: View Encrypted File Content (NEVER DO THIS)
        run: cat $HOME/secrets/secret.json